n=input('Escreva algo: ')
print('o tipo primitivo é',type(n))
print('é alfa numérico?',n.isalnum())
print('é numérico?',n.isnumeric())
print('é alfabético?',n.isalpha())
print('é todo minúsculo?',n.islower())
print('é todo maiúsculo?',n.isupper())
print('é capitalizado?',n.isascii())
